# Generated by Django 3.2.10 on 2022-01-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectjob',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
