# Generated by Django 3.2.10 on 2022-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceimage', '0003_auto_20220112_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedetectjob',
            name='name',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
